apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-global-secrets #{{ .Values.global.secretProviderClassName }}
  namespace: default
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  provider: azure
  secretObjects:
    - secretName: global-k8s-secrets #{{ .Values.global.secretsName }}
      type: Opaque
      data:
        - objectName: PERSONAL-PASSWORD
          key: PERSONAL_PASSWORD

        - objectName: PERSONAL-PASSWORD
          key: MONGODB_ROOT_PASSWORD

        - objectName: KEYCLOAK-ORDERS-SECRET-ID
          key: KEYCLOAK_ORDERS_SECRET_ID

        - objectName: SSL-TRUST-STORE-PASSWORD
          key: SSL_TRUST_STORE_PASSWORD

        - objectName: SSL-KEY-STORE-PASSWORD
          key: SSL_KEY_STORE_PASSWORD

        - objectName: AZURE-SERVICE-STORAGE-ACCOUNT-BLOB-STORAGE-MICROSERVICESLOKILOGS-ACCOUNT-KEY
          key: AZURE_SERVICE_STORAGE_ACCOUNT_BLOB_STORAGE_MICROSERVICESLOKILOGS_ACCOUNT_KEY

  parameters:
    usePodIdentity: "false"
    keyvaultName: "AppVaultStore"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecd50515-4475-4065-ad3a-c29be1b06e80"
    tenantId: "70d441cb-87ea-4640-ab2e-bf5af482bf0a"
    objects: |
      array:
        - |
          objectName: PERSONAL-PASSWORD
          objectType: secret
        - |
          objectName: SSL-KEY-STORE-PASSWORD
          objectType: secret
        - |
          objectName: SSL-TRUST-STORE-PASSWORD
          objectType: secret
        - |
          objectName: KEYCLOAK-ORDERS-SECRET-ID
          objectType: secret
        - |
          objectName: Truststore
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: Truststore.pfx
        - |
          objectName: Orders-keystore
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: Orders-keystore.pfx
        - |
          objectName: Products-keystore
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: Products-keystore.pfx
        - |
          objectName: Warehouse-keystore
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: Warehouse-keystore.pfx
        - |
          objectName: AZURE-SERVICE-STORAGE-ACCOUNT-BLOB-STORAGE-MICROSERVICESLOKILOGS-ACCOUNT-KEY
          objectType: secret






