spring:
  ssl:
    bundle:
      jks:
        products-client:
          keystore:
            location: file:${KEY_STORE_LOCATION:''}
            password: ${KEY_STORE_PASSWORD:''}
            type: PKCS12
            alias: keystore-products
          truststore:
            location: file:${TRUST_STORE_LOCATION:''}
            password: ${TRUST_STORE_PASSWORD:''}
            type: PKCS12















