spring:
  ssl:
    bundle:
      jks:
        products-client:
          keystore:
            location: file:${SSL_KEY_STORE_LOCATION:''}
            password: ${SSL_KEY_STORE_PASSWORD:''}
            type: PKCS12
            alias: keystore-products
          truststore:
            location: file:${SSL_TRUST_STORE_LOCATION:''}
            password: ${SSL_TRUST_STORE_PASSWORD:''}
            type: PKCS12















